[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python web_server_multi.py"
