[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = ["python3.11 -m pip install --upgrade pip", "python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 web_server_multi.py"
